---
- name: Common Configuration for All Nodes
  hosts: all
  become: yes
  roles:
    - common

- name: Configure Master Node (Jenkins, Nexus)
  hosts: master
  become: yes
  roles:
    - master

- name: Configure Worker Nodes (General, Monitoring)
  hosts: worker
  become: yes
  roles:
    - worker
